### ISSUE TITLE
moving Moov atom to beginning

### ISSUE THREAD

**Issue by tabraiz961** [vladjerca/FFMpegSharp#21]
mobile videos have thier metadata headers at the end of file.
I need to pass arguments to FFMPEG move the header to the beginning. Is there a way ???

**Comment by max619** [comment]
@tabraiz961, could you please write down which parameter you need?

**Comment by vladjerca** [comment]
@max619 

I think this is what we're looking for [movflags](https://blog.dareboost.com/en/2018/01/optimize-your-mp4-video-for-better-performance/#attachment_4175)

``` bash
 -movflags faststart
```

**Comment by vladjerca** [comment]
@tabraiz961 With the new `Convert` method available and thanks to argument builder@max619 worked on. You can easily implement a custom argument that you could pass to the builder yourself.
