### ISSUE TITLE
Implementation of multi-target project

### ISSUE THREAD

**Issue by max619** [vladjerca/FFMpegSharp#22]
I think it would be useful, if we would create multi-target build for .Net Standart and .Net Framework. To make this library availible under .Net Framework and .Net Core.
For now we have only one dependency that is not supported by Net Standart - System.Drawing
I'm offering to create build targets for .Net Framework. that includes System.Drawing and for .Net Standart, that doesn't

**Comment by vladjerca** [comment]
@max619 Help is always appreciated in this area!

**Comment by vladjerca** [comment]
@max619 Any updates on this?

**Comment by vladjerca** [comment]
Ported to `.Net Standard`, this project is being dropped in favor of https://github.com/vladjerca/FFMpegCore
