### ISSUE TITLE
hi , can support net core ?  Now net core seems to have ported the system.drawing class library.

### ISSUE THREAD

**Issue by mingyangzhu** [vladjerca/FFMpegSharp#25]

**Comment by vladjerca** [comment]
@mingyangzhu this is something I'm looking into, but it will not arrive soon as I want to offer a multi-platform solution once ported to .NET Core

**Comment by xiaoxin01** [comment]
@vladjerca Hi, Any progress? :)

**Comment by vladjerca** [comment]
@xiaoxin01 Ported to `.Net Standard`, this project is being dropped in favor of https://github.com/vladjerca/FFMpegCore
