### ISSUE TITLE
so strange about filesize

### ISSUE THREAD

**Issue by kergee** [vladjerca/FFMpegSharp#3]
in FFProbe.cs, I found file size from

> info.Size = Math.Round(videoSize + audioSize, 2);

but I think filesize should be fileInfo.Length?

**Comment by vladjerca** [comment]
It's equivalent, feel free to open a PR if you think the result is better this way.

**Comment by vladjerca** [comment]
It's equivalent, feel free to open a PR if you think the result is better this way.
