### ISSUE TITLE
FFMpegSharp.FFMPEG.Exceptions.FFMpegException: Error opening filters!

### ISSUE THREAD

**Issue by markuszeller** [vladjerca/FFMpegSharp#4]
When using ConvertTo method and any VideoSize is used which does not match VideoSize.Orginal, then it crashes with following exception:

`Unbehandelte Ausnahme: FFMpegSharp.FFMPEG.Exceptions.FFMpegException: Error opening filters!
   bei FFMpegSharp.FFMPEG.FFMpeg.RunProcess(String args, FileInfo output) in C:\Users\n4cer\Documents\Visual Studio 2017\Projects\FFMpegSharp-master\FFMpegSharp\FFMPEG\FFMpeg.cs:Zeile 372.
   bei FFMpegSharp.FFMPEG.FFMpeg.ToMp4(VideoInfo source, FileInfo output, Speed speed, VideoSize size, AudioQuality aQuality, Boolean multithread) in C:\Users\n4cer\Documents\Visual Studio 2017\Projects\FFMpegSharp-master\FFMpegSharp\FFMPEG\FFMpeg.cs:Zeile 111.
   bei FFMpegSharp.VideoInfo.ConvertTo(VideoType type, FileInfo output, Speed speed, VideoSize size, AudioQuality audio, Boolean multithread, Boolean tryToPurge) in C:\Users\n4cer\Documents\Visual Studio 2017\Projects\FFMpegSharp-master\FFMpegSharp\VideoInfo.cs:Zeile 229.
   bei FFMpegSharp.Example.Program.Main(String[] args) in c:\Users\n4cer\Documents\Visual Studio 2017\Projects\FFMpegSharp-master\FFMpegSharp.Example\Program.cs:Zeile 26.
`

The code looks like this:
`            outputFile = new FileInfo("test.mp4");
            video.ConvertTo(VideoType.Mp4, outputFile, Speed.UltraFast,
                VideoSize.Hd,
                AudioQuality.Hd,
                true,
                false);`

I could reproduce this using another Win10 machine in VS2017.

**Comment by WhiteLionATX** [comment]
Same here. While encoding with scaling works by command line (ffmpeg -i input.mp4 -vf scale=1280:720 output.mp4) this doesn´t work by using the wrapper lib of this project.

**Comment by vladjerca** [comment]
@markuszeller @WhiteLionATX I'll take a look in the following days.

**Comment by vladjerca** [comment]
@markuszeller the fix was pushed to master 👍
