### ISSUE TITLE
parsing double fails.

### ISSUE THREAD

**Issue by WhiteLionATX** [vladjerca/FFMpegSharp#5]
Using double.Parse like you did in this project fails for me (non US OS) because the way its implemented doesnt work on "my culture settings". In the way its implemented the parsing will just delete the separator eg: 123.456 will get 123456 after parsing.
You did things like:
numberData = double.Parse(dict["streams"][vid]["duration"]);
fix goes like this:
numberData = double.Parse(dict["streams"][vid]["duration"], CultureInfo.InvariantCulture);

**Comment by vladjerca** [comment]
I will update the implemenation. Sorry for the late response.
