### ISSUE TITLE
Reading Video file one frame at a time and writing to disk

### ISSUE THREAD

**Issue by karanmartian** [vladjerca/FFMpegSharp#6]
Hi,

I am reading an mp4 video file one frame at a time. After some manipulation on that frame I have a Bitmap frame that I want to write to an output mp4 file along with the original audio from the source mp4 file. How do I achieve this using your library?

**Comment by vladjerca** [comment]
@karanmartian I don't have a method implemented yet that allows joining of multiple images.

But I will update the API to support image sequencing to video.
