### ISSUE TITLE
how should i cost mp4 to  h264 codec mp4

### ISSUE THREAD

**Issue by debin168** [vladjerca/FFMpegSharp#7]
thank u for  u work

**Comment by vladjerca** [comment]
@debin168 I'm not sure if I understand correctly.

But if you convert to `mp4`, is uses the `LibX264` codec to achieve this.

You can take a look at the example app to see how to convert to `mp4` using the library.

https://github.com/vladjerca/FFMpegSharp/blob/57ccb970ae674f4b1cf1427034ea54863f81bdaa/FFMpegSharp.Example/Program.cs#L20

**Comment by vladjerca** [comment]
@debin168 I've update the codebase today to try to improve display compatibility by reinforcing the Yuv420p pixel format as recommended by FFMpeg [here](https://trac.ffmpeg.org/wiki/Encode/H.264#Encodingfordumbplayers).

**Comment by vladjerca** [comment]
@debin168 has the update solved your issue with mobile devices?
